### ISSUE TITLE
v1.0.0 milestone

### ISSUE THREAD

**Issue by desfero** [desfero/structlint#1]
- [x] Add `allowedImports` config option
- [x] Add support for dynamic imports and CommonJS imports
- [x] Add a full monorepo support
- [x] Add docs
- [x] #8 (support for `index.js` imports)
